### ISSUE TITLE
Unificar diagramas e protótipos no documento de Especificação de Software

### ISSUE THREAD

**Issue by petroniocandido** [Evanio/Sistema-Oficina-JR#4]

**Comment by rodrigocampos97** [comment]
Professor, no nosso diagrama de 2° Nível temos UC1.1 Cadastrar Clientes, UC1.2 Alterar Clientes, UC1.3 Excluir Clientes e UC1.4 Buscar Clientes.
Na descrição dos casos de uso, o senhor nos disse para unificar os casos de uso 1.1, 1.2 e 1.3. Também é necessário unifica-los nos diagramas de 2° Nível?

**Comment by petroniocandido** [comment]
Pode ter sido um erro de copiar e colar, faço o que estiver de acordo com a lógica do sistema.
